/**
 * Auth
 */
export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const SET_TOKEN = 'SET_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';

/**
 * Sign Up
 */
export const SIGNUP_BEGIN = 'SIGNUP_BEGIN';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_BAD_REQUEST = 'SIGNUP_BAD_REQUEST';
/**
 * Drawing
 */
export const DRAWING_REQUEST_BEGIN = 'DRAWING_REQUEST_BEGIN';
export const DRAWING_REQUEST_SUCCESS = 'DRAWING_REQUEST_SUCCESS';
export const DRAWING_REQUEST_FAILURE = 'DRAWING_REQUEST_FAILURE';

export const TOGGLE_IS_PUBLIC = 'TOGGLE_IS_PUBLIC';
export const SET_UPDATE_DATA = 'SET_UPDATE_DATA';
export const SET_DRAWING_TITLE = 'SET_DRAWING_TITLE';
export const SET_MODE = 'SET_MODE';

export const CREATE_BEGIN = 'CREATE_BEGIN';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const CREATE_FAILURE = 'CREATE_FAILURE';
/**
 * Drawing Editter
 */
export const SET_DRAWING = 'SET_DRAWING';
export const SET_COLOR = 'SET_COLOR';
export const SET_WEIGHT = 'SET_WEIGHT';
export const SET_UNDO_TRIGGER = 'SET_UNDO_TRIGGER';
export const SET_REDO_TRIGGER = 'SET_REDO_TRIGGER';
export const SET_POINTER_SPEED = 'SET_POINTER_SPEED';
export const SET_SAVE_TRIGGER = 'SET_SAVE_TRIGGER';
export const SET_LOAD_TRIGGER = 'SET_LOAD_TRIGGER';
export const SET_STOP_POINTER_TRIGGER = 'SET_STOP_POINTER_TRIGGER';

/**
 * Gallery
 */
export const SET_USER_GALLERY_BEGIN = 'SET_USER_GALLERY_BEGIN';
export const SET_USER_GALLERY_SUCCESS = 'SET_USER_GALLERY_SUCCES';
export const SET_USER_GALLERY_FAILURE = 'SET_USER_GALLERY_FAILURE';
export const SET_PUBLIC_GALLERY_BEGIN = 'SET_PUBLIC_GALLERY_BEGIN';
export const SET_PUBLIC_GALLERY_SUCCESS = 'SET_PUBLIC_GALLERY_SUCCES';
export const SET_PUBLIC_GALLERY_FAILURE = 'SET_PUBLIC_GALLERY_FAILURE';
export const SET_ALLDRAWINGS = 'SET_ALLDRAWINGS';
