/**
 * Drawging
 */
export const CHNAGE_MODE = 'CHNAGE_MODE';
export const GET_ALLDRAWINGS = 'GET_ALLDRAWINGS';
export const SET_DRAWINGID = 'SET_DRAWINGID';
export const SET_DRAWING = 'SET_DRAWING';
export const CHANGE_COLOR = 'CHANGE_COLOR';
export const CHANGE_WEIGHT = 'CHANGE_WEIGHT';
export const SET_UNDOTRIGGER = 'SET_UNDOTRIGGER';
export const SET_REDOTRIGGER = 'SET_REDOTRIGGER';
export const SET_POINTERSPEED = 'SET_POINTERSPEED';
export const SET_SAVETRIGGER = 'SET_SAVETRIGGER';
export const SET_LOADTRIGGER = 'SET_LOADTRIGGER';
export const SET_STOPPOINTERTRIGGER = 'SET_STOPPOINTERTRIGGER';
export const TOGGLE_ISPUBLIC = 'TOGGLE_ISPUBLIC';

export const SET_DRAWINGDATA = 'SET_DRAWINGDATA';
export const SET_DRAWINGIMGURL = 'SET_DRAWINGIMGURL';
export const SET_UPDATEDAT = 'SET_UPDATEDAT';